dns: 10.0.0.53
network_settings:
  home:
    network: home
    gateway: 10.0.0.1
    subnet: 10.0.0.0/24
    cidr: /24
    dns: "{{ dns }}"
    domain: home
  home_wifi:
    network: home
    gateway: 10.0.0.1
    cidr: /24
    dns: "{{ dns }}"
    domain: home
    ssid: Wi-Fi2
    password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      39663166346233343964383266363934363433353733646137386365666663393661653837336261
      3739383961366262623265623964346634663761363236330a663364656638643162303439383235
      34353839383566373263393934373036323337646339653961643461663439353765373735376132
      6132376232346339300a376239373736393434336532323937316233393232383337363564313335
      3264
  vpn:
    network: vpn
    subnet: 10.10.0.0/24
    endpoint: "{{ duck_dns_domain }}.duckdns.org:51820"
    dns: "{{ dns }}"
    port: 51820
    persistent_keepalive: 25
    public_key: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      61666262326664323664343431623536323765313836666261313230303662646135313030646161
      3235383332323639373732633465373832386437346134390a623065623433646231323033373236
      66313436373532393663646338356136346430383636623631336535636261336233393139383738
      3032383562316462610a653634303665353434643431663563653961383434643237323438323132
      63313331323165366334353337373762303363613439396235666561663732653637363463376264
      3538343161323033633339353136396335636661613561313631
